# Generated by Django 6.0.5 on 2026-05-08 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institutions',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('batch_name', models.CharField(help_text='e.g., SY 2025-2026 First Batch', max_length=100)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Data'), ('PROCESSING', 'AI Generating'), ('PROOFING', 'Awaiting Approval'), ('APPROVED', 'Approved by Institution'), ('PRINTING', 'Printing'), ('COMPLETED', 'Ready for Pickup'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL)),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.institution')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='id_backgrounds/')),
                ('card_width', models.PositiveIntegerField(default=638)),
                ('card_height', models.PositiveIntegerField(default=1012)),
                ('photo_x', models.PositiveIntegerField(default=169)),
                ('photo_y', models.PositiveIntegerField(default=180)),
                ('photo_width', models.PositiveIntegerField(default=300)),
                ('photo_height', models.PositiveIntegerField(default=350)),
                ('fields_config', models.JSONField(default=dict)),
                ('show_full_name', models.BooleanField(default=True)),
                ('show_student_id', models.BooleanField(default=True)),
                ('show_grade_level', models.BooleanField(default=True)),
                ('show_school_name', models.BooleanField(default=True)),
                ('show_school_year', models.BooleanField(default=True)),
                ('show_signature_line', models.BooleanField(default=True)),
                ('show_qr_code', models.BooleanField(default=True)),
                ('show_barcode', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='api.order')),
            ],
            options={
                'db_table': 'id_layouts',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('OPERATOR', 'Operator'), ('INSTITUTION', 'Institution'), ('COORDINATOR', 'Coordinator')], default='OPERATOR', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinators', to='api.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('grade_level', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('processed_photo', models.ImageField(blank=True, null=True, upload_to='processed_photos/')),
                ('photo_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('MANUAL_REVIEW', 'Manual Review')], default='PENDING', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_walk_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.order')),
            ],
            options={
                'db_table': 'students',
                'unique_together': {('order', 'student_id')},
            },
        ),
    ]
