# Generated by Django 6.0.5 on 2026-05-10 15:28

import api.models.students
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qr_code_data',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for QR code', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.students.Student.student_photo_path),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['qr_code_data'], name='students_qr_code_79675c_idx'),
        ),
    ]
