# Generated by Django 6.0.5 on 2026-05-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adminauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo_url',
            field=models.TextField(blank=True, help_text="Cloudinary URL to institution's logo", null=True),
        ),
    ]
