# Generated by Django 6.0.5 on 2026-05-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_institution_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinglog',
            name='level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20),
        ),
    ]
