# Generated by Django 6.0.5 on 2026-05-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_institution_suspended_at_institution_suspended_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='logo',
        ),
        migrations.AddField(
            model_name='institution',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL to institution's logo", max_length=500, null=True),
        ),
    ]
