# Generated by Django 6.0.5 on 2026-06-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_processinglog_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Data'), ('PROCESSING', 'AI Generating'), ('PROOFING', 'Awaiting Approval'), ('APPROVED', 'Approved by Institution'), ('PRINTING', 'Printing'), ('COMPLETED', 'Ready for Pickup'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Processing Failed')], default='PENDING', max_length=20),
        ),
    ]
