# Generated by Django 6.0.5 on 2026-06-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fail_reason',
            field=models.CharField(blank=True, default='', help_text="Values: 'no_qr', 'qr_not_found', 'no_face', 'no_layout', 'error'", max_length=100),
        ),
    ]
