# Generated by Django 6.0.5 on 2026-06-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_fail_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='original_photo_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the original uploaded photo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fail_reason',
            field=models.CharField(blank=True, default='', help_text="Reason for MANUAL_REVIEW: 'no_qr', 'qr_not_found', 'no_face', 'no_layout', 'error'", max_length=100),
        ),
    ]
