# Generated by Django 6.0.5 on 2026-06-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_coordinatorinvite'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coordinatorinvite',
            table='coordinator_invites',
        ),
    ]
