# Generated by Django 6.0.5 on 2026-06-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_coordinatorinvite_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_photographed',
            field=models.BooleanField(default=False),
        ),
    ]
