# Generated by Django 6.0.5 on 2026-06-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='idlayout',
            name='background_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='idlayout',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_backgrounds/'),
        ),
    ]
