# Generated by Django 4.2.23 on 2026-07-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_idlayout_background_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional SIS fields'),
        ),
    ]
