# Generated by Django 4.2.23 on 2026-09-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_student_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='processed_photo',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the rendered ID card', max_length=500, null=True),
        ),
    ]
