# Generated by Django 4.2.23 on 2026-09-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_student_processed_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='order_quota',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum numbers allowed; null means unlimited', null=True),
        ),
    ]
