# Generated by Django 4.2.23 on 2026-09-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_institution_order_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='contract_ends_at',
            field=models.DateTimeField(blank=True, help_text='Date when the contract ends. Used to trigger asset cleanup.', null=True),
        ),
    ]
