# Generated by Django 4.2.23 on 2026-09-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_institution_contract_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='idlayout',
            name='side',
            field=models.CharField(choices=[('FRONT', 'Front'), ('BACK', 'Back')], default='FRONT', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='idlayout',
            unique_together={('order', 'side')},
        ),
    ]
