# Generated by Django 4.2.23 on 2026-09-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_idlayout_side_alter_idlayout_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='processed_photo_back',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the rendered ID card back side', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='processed_photo',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the rendered ID card front side', max_length=500, null=True),
        ),
    ]
