# Generated by Django 4.2.23 on 2026-09-03 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_student_processed_photo_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invite_type', models.CharField(choices=[('OPERATOR', 'Operator'), ('INSTITUTION', 'Institution')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_invite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_invites',
            },
        ),
    ]
