# Generated by Django 4.2.23 on 2026-09-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_accountinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinvite',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
