# Generated by Django 4.2.23 on 2026-09-07 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_accountinvite_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idlayout',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='api.order'),
        ),
    ]
